### ISSUE TITLE
Having issues following setup for Oculus DK2

### ISSUE THREAD

**Issue by POEDaley** [NOLOVR/NOLO-Others#2]
Hello, I'm a bit new to working with OSVR, and I'm unable to find the OSVR-Oculus folder as mentioned in the setup instructions.  I have the nolo driver, oculus software, and HDK SDK installed.  Is there something I have missed?

Thanks,

**Comment by GXiaoyang** [comment]
hi,
@POEDaley 
OSVR-Oculus folder,you need download from the github.

**Comment by LyuzhouZ** [comment]
https://github.com/NOLOVR/NOLO-Others/tree/master/NOLO_Oculus_Steamvr/OSVR-Oculus
