### ISSUE TITLE
Firmware issue: duplicate and corrupt reports when controllers are active

### ISSUE THREAD

**Issue by lonetech** [NOLOVR/NOLO-Others#3]
Normally, the headset tracker transmits two 64 byte frames on USB at 60Hz. One is for controllers, the other for base station and headset tracker. 

When controllers are on, I receive twice as many packets, most of them duplicates. From time to time, a corrupt headset marker packet is received; the last three bytes of that indicate that it has been overwritten with controller data. 

It looks like there's a race condition in the radio reception code for the headset marker. 

This is not a critical bug, but does waste power. A workaround at driver level is to ignore corrupt or duplicate packets.

**Comment by LyuzhouZ** [comment]
We've updated the firmware and is now working on 120Hz.
