### ISSUE TITLE
Gear VR + NOLO Tetris app: provide the source code of the app, or at least use some service like Sideload VR or Construct VR.

### ISSUE THREAD

**Issue by mathieu-b** [NOLOVR/NOLO-Others#4]
As of now, the only way to "run" the application is to use [some wacky apps](https://play.google.com/store/apps/details?id=com.kunkunsoft.cardboardappforgearvr&hl=en) that kind of allow running Cardboard apps as if they were Gear VR apps.

Getting NOLO apps accepted on the Oculus Gear VR store seems very unlikely since they would not necessarily support other basic means of interacting like Gaze, Touch-pad, game pads, or Gear VR controllers.

The solution on your side would be to use platforms such as:
*  [Construct VR](https://www.constructvr.io/), Google Play link [here](https://play.google.com/store/apps/details?id=com.archonware.constructvr&hl=en).
*  [Sideload VR](http://sideloadvr.com/), Google Play link [here](https://play.google.com/store/apps/details?id=com.sideloadvr.market&hl=en) (worse ratings than Construct VR).

Both platform automatically inject the needed data in a given APK
(probably an OSIG file generated from the respective Android apps that the Gear VR user has to install first). Check them out :)

Regards.

**Comment by Hettylool** [comment]
actually,i have put my app on Oculus Home.
i have to add another way use touch-pad to play the app.
i will figure out Construct VR and Sideload VR.
what should i to to help the gearvr developer

**Comment by mathieu-b** [comment]
@Hettylool nice :)

**Comment by mathieu-b** [comment]
Hi @Hettylool 

Good to see that NOLO Tetris is now on Construct VR :)

However there's a problem: once opened, the app just starts in stereoscopic mode without first prompting to insert the device into the Gear VR headset.

My device is a Samsung Galaxy S7 with Android 7.0.

This might be due to a buggy Unity 3D version being used (I had that problem once while developing for Gear VR) or maybe the Oculus driver wasn't chosen diring the build, leaving the settings for Google Cardboard / Daydream.

Hopefully it will be an easy fix.
I really want to try the app :)

Regards.

**Comment by Hettylool** [comment]
@mathieu-b 
Hi, i have put a cardboard version on googleplay. and i have put a GearVR version in SamsungStore.not on construct vr.

**Comment by mathieu-b** [comment]
Hi @Hettylool 
I can't seem to find NOLO Tetris, nor in Samsung Apps, nor in the Oculus store.

Note that Construct VR is mainly intended for Gear VR, basically to circumvent the OSIG file limitation and Oculus store approval process.

You need to upload the Gear VR version too on Construct VR.

Or if you could provide any link for the Gear VR apk... 
even if I doubt it would work, due to missing OSIG file from my device (and anyone else's).
That's the whole point behind using Construct VR.

Regards.

**Comment by Hettylool** [comment]
https://www.constructvr.io/gearvr/Sks5Bw5_W

**Comment by mathieu-b** [comment]
@Hettylool

I've just read this notice from Construct VR:

http://mailchi.mp/41df6ecf76c0/constructvr-is-shutting-down

They are shutting it down :(
