### ISSUE TITLE
360.dll No luck with it with pimax.

### ISSUE THREAD

**Issue by MykeyRM** [NOLOVR/NOLO-Others#7]
Iv'e updated all software, moved the .dll to the correct location with services terminated with admin elevation, repaired the nolo devices, removed steamvr.settings file and re-done room setups and steam fails to see any of the nolo devices with the 360.dll loaded. If it does happen to see the nolo with the 360.dll loaded then the orientation is still wrong anyway. The .dll also spits call errors when you try loading up the nolo software with it.  

Its just been many hours of frustration which is a shame because the front facing only is a mood killer. 
No VR should be designed with one direction limitations. 
hopefully these is an answer out there that can get this working for me.

**Comment by Conzar** [comment]
Are you using this with OSVR?  If so, we are working on an open source solution for 360 'ceiling' mode.

**Comment by MykeyRM** [comment]
Im using it with steam games and pimax 4k where it appears to be emulating the vive. With the standard front only view it works fine. also seems to work in the nolo visualiser but steam and games always seem to have the front facing orientation.

**Comment by Aureltouch** [comment]
360 dll  doesn t work with latest piplay

NOLO Soft:Form loading with error...Impossible de trouver le point d'entrée 'disConnenct_FunCallBack' dans la DLL 'NoLo_USBHID.dll'

**Comment by LyuzhouZ** [comment]
The new Pimax software will allow you to choose between 180/360. Users no longer need to replace dlls to achieve this.
